// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hi.proto

package hi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HiRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiRequest) Reset()         { *m = HiRequest{} }
func (m *HiRequest) String() string { return proto.CompactTextString(m) }
func (*HiRequest) ProtoMessage()    {}
func (*HiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d092a8920edeec73, []int{0}
}

func (m *HiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiRequest.Unmarshal(m, b)
}
func (m *HiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiRequest.Marshal(b, m, deterministic)
}
func (m *HiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiRequest.Merge(m, src)
}
func (m *HiRequest) XXX_Size() int {
	return xxx_messageInfo_HiRequest.Size(m)
}
func (m *HiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HiRequest proto.InternalMessageInfo

func (m *HiRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HiReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiReply) Reset()         { *m = HiReply{} }
func (m *HiReply) String() string { return proto.CompactTextString(m) }
func (*HiReply) ProtoMessage()    {}
func (*HiReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d092a8920edeec73, []int{1}
}

func (m *HiReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiReply.Unmarshal(m, b)
}
func (m *HiReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiReply.Marshal(b, m, deterministic)
}
func (m *HiReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiReply.Merge(m, src)
}
func (m *HiReply) XXX_Size() int {
	return xxx_messageInfo_HiReply.Size(m)
}
func (m *HiReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HiReply.DiscardUnknown(m)
}

var xxx_messageInfo_HiReply proto.InternalMessageInfo

func (m *HiReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HiRequest)(nil), "hi.HiRequest")
	proto.RegisterType((*HiReply)(nil), "hi.HiReply")
}

func init() { proto.RegisterFile("hi.proto", fileDescriptor_d092a8920edeec73) }

var fileDescriptor_d092a8920edeec73 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0xc8, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0xc8, 0x54, 0x92, 0xe7, 0xe2, 0xf4, 0xc8, 0x0c, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x94, 0xb9, 0xd8, 0x41, 0x0a, 0x0a, 0x72, 0x2a, 0x85,
	0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x61, 0x2a, 0x60, 0x5c, 0x23, 0x23, 0x90,
	0x29, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xaa, 0x5c, 0xac, 0xc1, 0x89, 0x95, 0x1e,
	0x99, 0x42, 0xbc, 0x7a, 0x19, 0x99, 0x7a, 0x70, 0xd3, 0xa5, 0xb8, 0x61, 0xdc, 0x82, 0x9c, 0x4a,
	0x25, 0x86, 0x24, 0x36, 0xb0, 0x23, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x07, 0xa9,
	0x30, 0x90, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HiServiceClient is the client API for HiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HiServiceClient interface {
	SayHi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiReply, error)
}

type hiServiceClient struct {
	cc *grpc.ClientConn
}

func NewHiServiceClient(cc *grpc.ClientConn) HiServiceClient {
	return &hiServiceClient{cc}
}

func (c *hiServiceClient) SayHi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiReply, error) {
	out := new(HiReply)
	err := c.cc.Invoke(ctx, "/hi.HiService/SayHi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HiServiceServer is the server API for HiService service.
type HiServiceServer interface {
	SayHi(context.Context, *HiRequest) (*HiReply, error)
}

func RegisterHiServiceServer(s *grpc.Server, srv HiServiceServer) {
	s.RegisterService(&_HiService_serviceDesc, srv)
}

func _HiService_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HiServiceServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hi.HiService/SayHi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HiServiceServer).SayHi(ctx, req.(*HiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hi.HiService",
	HandlerType: (*HiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _HiService_SayHi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hi.proto",
}
